service: cadastro-pacientes

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  # you can overwrite defaults here
  stage: dev
  region: us-east-1

functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: pacientes
          method: get
  obterPacientes:
    handler: handler.obterPacientes
    events:
      - http:
          path: pacientes/{id}
          method: get
